In [9]:
import numpy as np


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


x = np.array([0.5, 0.1, -0.2])
target = 0.6
learnrate = 0.5
maxerror=0.01

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])
for i in range(10000):
    ## Forward pass
    hidden_layer_input = np.dot(x, weights_input_hidden)
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
    output = sigmoid(output_layer_in)
    print('Output',output)
## Backwards pass
## TODO: Calculate output error
    error = target - output
# TODO: Calculate error term for output layer
    output_error_term = error * output * (1 - output)

# TODO: Calculate error term for hidden layer
    hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                            hidden_layer_output * (1 - hidden_layer_output)
    

# TODO: Calculate change in weights for hidden layer to output layer
    delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
    delta_w_i_h = learnrate * hidden_error_term * x[:, None]
    print('Change in weights for hidden layer to output layer:')
    print(delta_w_h_o)
    print('Change in weights for input layer to hidden layer:')
    print(delta_w_i_h)
# to exit the loop
    if abs(error)<=maxerror:
        break
    else:
        weights_input_hidden=weights_input_hidden+delta_w_i_h
        weights_hidden_output=weights_hidden_output+delta_w_h_o
        
print('final Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('final Change in weights for input layer to hidden layer:')
print(delta_w_i_h)
print('no. of etteration')
print(i)

print(output)

Output 0.48497343084992534
Change in weights for hidden layer to output layer:
[0.00804047 0.00555918]
Change in weights for input layer to hidden layer:
[[ 1.77005547e-04 -5.11178506e-04]
 [ 3.54011093e-05 -1.02235701e-04]
 [-7.08022187e-05  2.04471402e-04]]
Output 0.4866410689015305
Change in weights for hidden layer to output layer:
[0.00792578 0.00547859]
Change in weights for input layer to hidden layer:
[[ 1.88498423e-04 -4.94491812e-04]
 [ 3.76996846e-05 -9.88983623e-05]
 [-7.53993692e-05  1.97796725e-04]]
Output 0.4882849533392762
Change in weights for hidden layer to output layer:
[0.00781252 0.00539905]
Change in weights for input layer to hidden layer:
[[ 1.99422688e-04 -4.78300228e-04]
 [ 3.98845375e-05 -9.56600457e-05]
 [-7.97690751e-05  1.91320091e-04]]
Output 0.4899053634712677
Change in weights for hidden layer to output layer:
[0.00770069 0.00532056]
Change in weights for input layer to hidden layer:
[[ 2.09796775e-04 -4.62590851e-04]
 [ 4.19593549e-05 -9.25181702e-05]